### ISSUE TITLE
Invalid DNS-ID with verify=off and IP-based host

### ISSUE THREAD

**Issue by bjo81** [privacyidea/privacyidea-ldap-proxy#42]
While trying to use a Privacy Idea on https://10.0.0.xy/ and verfiy=off the following exception occurs:

```
2018-04-23T15:10:32+0200 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] Error during info_callback
	Traceback (most recent call last):
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/twisted/protocols/tls.py", line 415, in dataReceived
	    self._checkHandshakeStatus()
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/twisted/protocols/tls.py", line 335, in _checkHandshakeStatus
	    self._tlsConnection.do_handshake()
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1425, in do_handshake
	    result = _lib.SSL_do_handshake(self._ssl)
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/OpenSSL/SSL.py", line 917, in wrapper
	    callback(Connection._reverse_mapping[ssl], where, return_code)
	--- <exception caught here> ---
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1151, in infoCallback
	    return wrapped(connection, where, ret)
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/twisted/internet/_sslverify.py", line 1250, in _identityVerifyingInfoCallback
	    verifyHostname(connection, self._hostnameASCII)
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/service_identity/pyopenssl.py", line 48, in verify_hostname
	    obligatory_ids=[DNS_ID(hostname)],
	  File "/opt/privacyidea-ldap-proxy/lib/python2.7/site-packages/service_identity/_common.py", line 245, in __init__
	    raise ValueError("Invalid DNS-ID.")
	exceptions.ValueError: Invalid DNS-ID.
	
2018-04-23T15:10:32+0200 [pi_ldapproxy.proxy#critical] Could not bind
	Traceback (most recent call last):
	Failure: twisted.web._newclient.RequestTransmissionFailed: [<twisted.python.failure.Failure exceptions.ValueError: Invalid DNS-ID.>]
	
2018-04-23T15:10:32+0200 [pi_ldapproxy.proxy#info] Sending BindResponse "invalid credentials": LDAP Proxy failed.
```

**Comment by cornelinux** [comment]
@fredreichbier any idea on this?

**Comment by bjo81** [comment]
No, the CN is simply "privacyidea".

**Comment by fredreichbier** [comment]
Ah, on a second thought, this hints at a deeper issue:
Currently, with ``verify = false``, the LDAP proxy apparently still does hostname validation of the certificate, which is why you even see the referenced error. I guess, if ``verify = false`` is set, the LDAP proxy should not even validate the hostname.
